In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import sys
ROOT = Path.cwd().parent.parent
sys.path.append(str(ROOT))
sys.path.append(str(ROOT / 'src'))
from src.perturbation.models.classifiers.rf_classifier import RFClassifier
from src.perturbation.models.classifiers.xgboost_classifier import XGBoostClassifier
from src.perturbation.models.classifiers.lgbm_classifier import LightGBMClassifier
from imblearn.over_sampling import SMOTEN
from src.loading_data.load_data import get_clean_2022
from src.perturbation.create_perturbations import preprocess_perturbation


c:\Users\fergu\Documents\GitHub\london_sport2\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
xgb_classifier = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\XGBoostClassifier.sav'
rfclas_path = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\RFClassifier.sav'
lightgbm_classifier = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\LightGBMClassifier.sav'
with open(xgb_classifier, 'rb') as file:
    xgb_classifier = pickle.load(file)
with open(rfclas_path, 'rb') as file:
    rfclas_path = pickle.load(file)
with open(lightgbm_classifier, 'rb') as file:
    lightgbm_classifier = pickle.load(file)


In [3]:
models = [xgb_classifier, rfclas_path, lightgbm_classifier]
for model in models:
    print('________________________________')
    print(model.name)
    print(model.get_confusion())
    print(f'F1 Score: {model.get_f1()}')
    print(f'ROC AUC Score: {model.get_roc_auc()}')
    print(f'Accuracy: {model.get_accuracy()}')


________________________________
XGBoostClassifier
[[ 84  15 153]
 [ 26   8 139]
 [108  48 969]]
F1 Score: 0.41175287810838584
ROC AUC Score: 0.6165926571584889
Accuracy: 0.6845161290322581
________________________________
RFClassifier
[[  45    0  207]
 [  17    3  153]
 [  49    2 1074]]
F1 Score: 0.37367737877864365
ROC AUC Score: 0.6305502050816759
Accuracy: 0.7238709677419355
________________________________
LightGBMClassifier
[[ 87   7 158]
 [ 23   9 141]
 [122  33 970]]
F1 Score: 0.416981481574783
ROC AUC Score: None
Accuracy: 0.687741935483871


In [4]:
df = get_clean_2022()

['Gend3', 'Disab2_POP', 'Age9', 'Eth7', 'NSSEC5', 'Educ6', 'IMD10', 'Child4', 'WorkStat8', 'HHLiv9', 'serial', 'year', 'LCA_Class', 'MEMS7_ALL']
Data loaded with zero missing values.
Loaded primary frame...
Loaded secondary frame...
Merged Frames.
Dropped NAN values


In [5]:
df_copy = df.copy()

In [6]:
df.head()

,serial,year,LCA_Class,Age9,Gend3,Eth7,Disab2_POP,Educ6,NSSEC5,IMD10,...,inclus_b,inclus_c,anxious,comm1,comm2,happy,indev,indevtry,lone,worthw
3,2.205902e+14,2022/23,2.0,6.0,1.0,1.0,1.0,1.0,3.0,4.0,...,1.0,2.0,5.0,3.0,2.0,7.0,4.0,4.0,4.0,7.0
4,2.205902e+14,2022/23,23.0,7.0,2.0,1.0,1.0,5.0,4.0,8.0,...,3.0,3.0,10.0,3.0,2.0,0.0,3.0,3.0,1.0,0.0
7,2.205903e+14,2022/23,14.0,4.0,2.0,1.0,2.0,1.0,1.0,3.0,...,2.0,2.0,2.0,3.0,3.0,8.0,1.0,1.0,3.0,10.0
10,2.206901e+14,2022/23,7.0,4.0,2.0,7.0,2.0,1.0,1.0,2.0,...,2.0,4.0,6.0,4.0,3.0,6.0,4.0,4.0,4.0,8.0
11,2.206902e+14,2022/23,19.0,4.0,2.0,4.0,2.0,1.0,4.0,5.0,...,3.0,4.0,2.0,3.0,4.0,9.0,4.0,4.0,2.0,10.0


In [7]:
X_train, X_test, Y_train, Y_test, test_set_clusters = preprocess_perturbation(df, 'LCA_Class', 'active_status', ['Gend3', 'Eth7', 'WorkStat8', 'HHLiv9'])

Keep columns : ['Age9', 'Disab2_POP', 'Educ6', 'NSSEC5', 'IMD10', 'Child4', 'Motiva_POP', 'motivd_POP', 'inclus_a', 'inclus_b', 'inclus_c', 'anxious', 'comm1', 'comm2', 'happy', 'indev', 'indevtry', 'lone', 'worthw', 'Gend3_1.0', 'Gend3_2.0', 'Gend3_3.0', 'Eth7_1.0', 'Eth7_2.0', 'Eth7_3.0', 'Eth7_4.0', 'Eth7_5.0', 'Eth7_6.0', 'Eth7_7.0', 'WorkStat8_0.0', 'WorkStat8_1.0', 'WorkStat8_2.0', 'WorkStat8_3.0', 'WorkStat8_4.0', 'WorkStat8_5.0', 'WorkStat8_6.0', 'WorkStat8_7.0', 'HHLiv9_0.0', 'HHLiv9_1.0', 'HHLiv9_2.0', 'HHLiv9_3.0', 'HHLiv9_4.0', 'HHLiv9_5.0', 'HHLiv9_6.0', 'HHLiv9_7.0', 'HHLiv9_8.0']
X_train cols:
Index(['Age9', 'Disab2_POP', 'Educ6', 'NSSEC5', 'IMD10', 'Child4',
       'Motiva_POP', 'motivd_POP', 'inclus_a', 'inclus_b', 'inclus_c',
       'anxious', 'comm1', 'comm2', 'happy', 'indev', 'indevtry', 'lone',
       'worthw', 'Gend3_1.0', 'Gend3_2.0', 'Gend3_3.0', 'Eth7_1.0', 'Eth7_2.0',
       'Eth7_3.0', 'Eth7_4.0', 'Eth7_5.0', 'Eth7_6.0', 'Eth7_7.0',
       'WorkStat8_0.0', '

In [8]:
X_train

,Age9,Disab2_POP,Educ6,NSSEC5,IMD10,Child4,Motiva_POP,motivd_POP,inclus_a,inclus_b,...,WorkStat8_7.0,HHLiv9_0.0,HHLiv9_1.0,HHLiv9_2.0,HHLiv9_3.0,HHLiv9_4.0,HHLiv9_5.0,HHLiv9_6.0,HHLiv9_7.0,HHLiv9_8.0
9825,4.0,1.0,1.0,1.0,10.0,4.0,1.0,4.0,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4034,8.0,1.0,1.0,5.0,8.0,1.0,1.0,5.0,3.0,2.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
189,4.0,1.0,1.0,1.0,5.0,2.0,1.0,4.0,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2050,4.0,1.0,1.0,1.0,8.0,2.0,1.0,5.0,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
12453,3.0,1.0,1.0,1.0,3.0,1.0,3.0,4.0,2.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7124,4.0,1.0,2.0,1.0,9.0,3.0,1.0,4.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
11805,8.0,1.0,1.0,5.0,3.0,1.0,3.0,4.0,3.0,3.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
9774,5.0,1.0,1.0,1.0,6.0,3.0,2.0,5.0,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8184,5.0,0.0,1.0,1.0,3.0,1.0,2.0,4.0,2.0,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [9]:
X_train.columns

Index(['Age9', 'Disab2_POP', 'Educ6', 'NSSEC5', 'IMD10', 'Child4',
       'Motiva_POP', 'motivd_POP', 'inclus_a', 'inclus_b', 'inclus_c',
       'anxious', 'comm1', 'comm2', 'happy', 'indev', 'indevtry', 'lone',
       'worthw', 'Gend3_1.0', 'Gend3_2.0', 'Gend3_3.0', 'Eth7_1.0', 'Eth7_2.0',
       'Eth7_3.0', 'Eth7_4.0', 'Eth7_5.0', 'Eth7_6.0', 'Eth7_7.0',
       'WorkStat8_0.0', 'WorkStat8_1.0', 'WorkStat8_2.0', 'WorkStat8_3.0',
       'WorkStat8_4.0', 'WorkStat8_5.0', 'WorkStat8_6.0', 'WorkStat8_7.0',
       'HHLiv9_0.0', 'HHLiv9_1.0', 'HHLiv9_2.0', 'HHLiv9_3.0', 'HHLiv9_4.0',
       'HHLiv9_5.0', 'HHLiv9_6.0', 'HHLiv9_7.0', 'HHLiv9_8.0'],
      dtype='str')

In [10]:
def smote_resample(X_train : pd.DataFrame, Y_train : pd.Series, k_neighbors : int = 5, strategy : tuple = (800,800)):
    smote = SMOTEN(
        k_neighbors= k_neighbors, 
        sampling_strategy= {0 : strategy[0], 1: strategy[1]}, 
        random_state = 42
    )
    X_train_smote, Y_train_smote = smote.fit_resample(X_train, Y_train)

    print(f'Pre smote: {X_train.shape}')
    print(f'Post smote: {X_train_smote.shape}')

    print(f'Pre smote: {Y_train.value_counts()}')
    print(f'Post smote: {Y_train_smote.value_counts()}')

    return X_train_smote, Y_train_smote

In [11]:
X_train_smote, Y_train_smote = smote_resample(X_train, Y_train)

Pre smote: (2628, 46)
Post smote: (3521, 46)
Pre smote: active_status
2.0    1921
0.0     437
1.0     270
Name: count, dtype: int64
Post smote: active_status
2.0    1921
1.0     800
0.0     800
Name: count, dtype: int64


In [12]:
X_train_smote['happy'].value_counts()

happy
8.0     819
7.0     788
9.0     468
6.0     441
5.0     384
10.0    306
4.0     155
3.0      77
0.0      36
2.0      35
1.0      12
Name: count, dtype: int64

In [13]:
X_train['happy'].value_counts()

happy
8.0     621
7.0     536
9.0     399
6.0     294
10.0    264
5.0     255
4.0     122
3.0      70
2.0      30
0.0      25
1.0      12
Name: count, dtype: int64