In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import sys
ROOT = Path.cwd().parent.parent
sys.path.append(str(ROOT))
sys.path.append(str(ROOT / 'src'))
from src.perturbation.models.classifiers.rf_classifier import RFClassifier
from src.perturbation.models.classifiers.xgboost_classifier import XGBoostClassifier
from src.perturbation.models.classifiers.lgbm_classifier import LightGBMClassifier
from imblearn.over_sampling import SMOTEN
from src.loading_data.load_data import get_clean_2022



c:\Users\fergu\Documents\GitHub\london_sport2\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
xgb_classifier = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\XGBoostClassifier.sav'
rfclas_path = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\RFClassifier.sav'
lightgbm_classifier = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\LightGBMClassifier.sav'
xg_smote1 = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\classifiers\1_XGBoostClassifier.sav'
xg_smote4 = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\classifiers\4_XGBoostClassifier.sav'
with open(xgb_classifier, 'rb') as file:
    xgb_classifier = pickle.load(file)
with open(rfclas_path, 'rb') as file:
    rfclas_path = pickle.load(file)
with open(lightgbm_classifier, 'rb') as file:
    lightgbm_classifier = pickle.load(file)
with open(xg_smote1, 'rb') as file:
    xg_smote1 = pickle.load(file)
with open(xg_smote4, 'rb') as file:
    xg_smote = pickle.load(file)


In [3]:
models = [xgb_classifier, rfclas_path, lightgbm_classifier, xg_smote]
for model in models:
    print('________________________________')
    print(model.name)
    print(model.get_confusion())
    print(f'F1 Score: {model.get_f1()}')
    print(f'ROC AUC Score: {model.get_roc_auc()}')
    print(f'Accuracy: {model.get_accuracy()}')


________________________________
XGBoostClassifier
[[ 84  15 153]
 [ 26   8 139]
 [108  48 969]]
F1 Score: 0.41175287810838584
ROC AUC Score: 0.6165926571584889
Accuracy: 0.6845161290322581
________________________________
RFClassifier
[[  45    0  207]
 [  17    3  153]
 [  49    2 1074]]
F1 Score: 0.37367737877864365
ROC AUC Score: 0.6305502050816759
Accuracy: 0.7238709677419355
________________________________
LightGBMClassifier
[[ 87   7 158]
 [ 23   9 141]
 [122  33 970]]
F1 Score: 0.416981481574783
ROC AUC Score: None
Accuracy: 0.687741935483871
________________________________
XGBoostClassifier
[[  72    7  211]
 [  26    7  167]
 [ 102   29 1132]]
F1 Score: 0.3893116679711528
ROC AUC Score: 0.605821049590011
Accuracy: 0.6908157444381061


In [4]:
from pathlib import Path

model_folder = ROOT / 'src' / 'perturbation' / 'models' / 'saved_models' / 'classifiers'
file_paths = [(file, file.name) for file in model_folder.iterdir()]
file_paths

[(WindowsPath('c:/Users/fergu/Documents/GitHub/london_sport2/src/perturbation/models/saved_models/classifiers/0_XGBoostClassifier.sav'),
  '0_XGBoostClassifier.sav'),
 (WindowsPath('c:/Users/fergu/Documents/GitHub/london_sport2/src/perturbation/models/saved_models/classifiers/101_XGBoostClassifier.sav'),
  '101_XGBoostClassifier.sav'),
 (WindowsPath('c:/Users/fergu/Documents/GitHub/london_sport2/src/perturbation/models/saved_models/classifiers/102_RFClassifier.sav'),
  '102_RFClassifier.sav'),
 (WindowsPath('c:/Users/fergu/Documents/GitHub/london_sport2/src/perturbation/models/saved_models/classifiers/103_LightGBMClassifier.sav'),
  '103_LightGBMClassifier.sav'),
 (WindowsPath('c:/Users/fergu/Documents/GitHub/london_sport2/src/perturbation/models/saved_models/classifiers/13_RFClassifier.sav'),
  '13_RFClassifier.sav'),
 (WindowsPath('c:/Users/fergu/Documents/GitHub/london_sport2/src/perturbation/models/saved_models/classifiers/14_RFClassifier.sav'),
  '14_RFClassifier.sav'),
 (WindowsP

In [5]:
best_f1 = float('-inf')
best_model = None
for path, file_name in file_paths:
    with open(path, 'rb') as file:
        model = pickle.load(file)
        if best_f1 < model.get_f1():
            best_f1 = model.get_f1()
            best_model = file_name
        print('________________________________')
        print(file_name)
        print(model.get_confusion())
        print(f'F1 Score: {model.get_f1()}')
        print(f'ROC AUC Score: {model.get_roc_auc()}')
        print(f'Accuracy: {model.get_accuracy()}')
print('__________________________')
print('__________________________')
print(f'BEST Model:\n>>>> Name: {best_model}\n>>>> F1: {best_f1}')

________________________________
0_XGBoostClassifier.sav
[[  82   17  191]
 [  30   10  160]
 [ 115   46 1102]]
F1 Score: 0.4006540850146904
ROC AUC Score: 0.5983667194510425
Accuracy: 0.6811180832857958
________________________________
101_XGBoostClassifier.sav
[[  72    8  210]
 [  29    6  165]
 [  93   37 1133]]
F1 Score: 0.38769491636178494
ROC AUC Score: 0.5957920363848163
Accuracy: 0.6908157444381061
________________________________
102_RFClassifier.sav
[[153  26 111]
 [107  11  82]
 [750 100 413]]
F1 Score: 0.2475380266791596
ROC AUC Score: 0.477390173232861
Accuracy: 0.3291500285225328
________________________________
103_LightGBMClassifier.sav
[[  78    0  212]
 [  39    0  161]
 [ 163    0 1100]]
F1 Score: 0.3592592592592592
ROC AUC Score: 0.5448549794777987
Accuracy: 0.6719908727895038
________________________________
13_RFClassifier.sav
[[  46    0  244]
 [  18    3  179]
 [  51    3 1209]]
F1 Score: 0.36383995601371844
ROC AUC Score: 0.6264366667121705
Accuracy: 0.7176269