In [5]:
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import sys
ROOT = Path.cwd().parent.parent
sys.path.append(str(ROOT))
sys.path.append(str(ROOT / 'src'))
from src.perturbation.models.classifiers.rf_classifier import RFClassifier
from src.perturbation.models.classifiers.xgboost_classifier import XGBoostClassifier
from src.perturbation.models.classifiers.lgbm_classifier import LightGBMClassifier
from imblearn.over_sampling import SMOTEN
from src.loading_data.load_data import get_clean_2022



In [6]:
xgb_classifier = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\XGBoostClassifier.sav'
rfclas_path = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\RFClassifier.sav'
lightgbm_classifier = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\LightGBMClassifier.sav'
xg_smote1 = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\classifiers\1_XGBoostClassifier.sav'
xg_smote4 = r'C:\Users\fergu\Documents\GitHub\london_sport2\src\perturbation\models\saved_models\classifiers\4_XGBoostClassifier.sav'
with open(xgb_classifier, 'rb') as file:
    xgb_classifier = pickle.load(file)
with open(rfclas_path, 'rb') as file:
    rfclas_path = pickle.load(file)
with open(lightgbm_classifier, 'rb') as file:
    lightgbm_classifier = pickle.load(file)
with open(xg_smote1, 'rb') as file:
    xg_smote1 = pickle.load(file)
with open(xg_smote4, 'rb') as file:
    xg_smote = pickle.load(file)


In [7]:
models = [xgb_classifier, rfclas_path, lightgbm_classifier, xg_smote]
for model in models:
    print('________________________________')
    print(model.name)
    print(model.get_confusion())
    print(f'F1 Score: {model.get_f1()}')
    print(f'ROC AUC Score: {model.get_roc_auc()}')
    print(f'Accuracy: {model.get_accuracy()}')


________________________________
XGBoostClassifier
[[ 84  15 153]
 [ 26   8 139]
 [108  48 969]]
F1 Score: 0.41175287810838584
ROC AUC Score: 0.6165926571584889
Accuracy: 0.6845161290322581
________________________________
RFClassifier
[[  45    0  207]
 [  17    3  153]
 [  49    2 1074]]
F1 Score: 0.37367737877864365
ROC AUC Score: 0.6305502050816759
Accuracy: 0.7238709677419355
________________________________
LightGBMClassifier
[[ 87   7 158]
 [ 23   9 141]
 [122  33 970]]
F1 Score: 0.416981481574783
ROC AUC Score: None
Accuracy: 0.687741935483871
________________________________
XGBoostClassifier
[[  69    8  213]
 [  28    5  167]
 [  90   36 1137]]
F1 Score: 0.38248481006056717
ROC AUC Score: 0.5948583808847754
Accuracy: 0.6908157444381061
